<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CountryPhoneCode;

class CountryPhoneCodeSeeder extends Seeder
{
    public function run()
    {
        $countries = [
               ['name' => 'Afghanistan', 'iso_code' => 'AF', 'phone_code' => '+93'],
    ['name' => 'Albania', 'iso_code' => 'AL', 'phone_code' => '+355'],
    ['name' => 'Algeria', 'iso_code' => 'DZ', 'phone_code' => '+213'],
    ['name' => 'American Samoa', 'iso_code' => 'AS', 'phone_code' => '+1684'],
    ['name' => 'Andorra', 'iso_code' => 'AD', 'phone_code' => '+376'],
    ['name' => 'Angola', 'iso_code' => 'AO', 'phone_code' => '+244'],
    ['name' => 'Anguilla', 'iso_code' => 'AI', 'phone_code' => '+1264'],
    ['name' => 'Antarctica', 'iso_code' => 'AQ', 'phone_code' => '+672'],
    ['name' => 'Antigua And Barbuda', 'iso_code' => 'AG', 'phone_code' => '+1268'],
    ['name' => 'Argentina', 'iso_code' => 'AR', 'phone_code' => '+54'],
    ['name' => 'Armenia', 'iso_code' => 'AM', 'phone_code' => '+374'],
    ['name' => 'Aruba', 'iso_code' => 'AW', 'phone_code' => '+297'],
    ['name' => 'Australia', 'iso_code' => 'AU', 'phone_code' => '+61'],
    ['name' => 'Austria', 'iso_code' => 'AT', 'phone_code' => '+43'],
    ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'phone_code' => '+994'],
    ['name' => 'Bahamas', 'iso_code' => 'BS', 'phone_code' => '+1242'],
    ['name' => 'Bahrain', 'iso_code' => 'BH', 'phone_code' => '+973'],
    ['name' => 'Bangladesh', 'iso_code' => 'BD', 'phone_code' => '+880'],
    ['name' => 'Barbados', 'iso_code' => 'BB', 'phone_code' => '+1246'],
    ['name' => 'Belarus', 'iso_code' => 'BY', 'phone_code' => '+375'],
    ['name' => 'Belgium', 'iso_code' => 'BE', 'phone_code' => '+32'],
    ['name' => 'Belize', 'iso_code' => 'BZ', 'phone_code' => '+501'],
    ['name' => 'Benin', 'iso_code' => 'BJ', 'phone_code' => '+229'],
    ['name' => 'Bermuda', 'iso_code' => 'BM', 'phone_code' => '+1441'],
    ['name' => 'Bhutan', 'iso_code' => 'BT', 'phone_code' => '+975'],
    ['name' => 'Bolivia', 'iso_code' => 'BO', 'phone_code' => '+591'],
    ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'phone_code' => '+387'],
    ['name' => 'Botswana', 'iso_code' => 'BW', 'phone_code' => '+267'],
    ['name' => 'Brazil', 'iso_code' => 'BR', 'phone_code' => '+55'],
    ['name' => 'Brunei', 'iso_code' => 'BN', 'phone_code' => '+673'],
    ['name' => 'Bulgaria', 'iso_code' => 'BG', 'phone_code' => '+359'],
    ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'phone_code' => '+226'],
    ['name' => 'Burundi', 'iso_code' => 'BI', 'phone_code' => '+257'],
    ['name' => 'Cambodia', 'iso_code' => 'KH', 'phone_code' => '+855'],
    ['name' => 'Cameroon', 'iso_code' => 'CM', 'phone_code' => '+237'],
    ['name' => 'Canada', 'iso_code' => 'CA', 'phone_code' => '+1'],
    ['name' => 'Cape Verde', 'iso_code' => 'CV', 'phone_code' => '+238'],
    ['name' => 'Cayman Islands', 'iso_code' => 'KY', 'phone_code' => '+1345'],
    ['name' => 'Central African Republic', 'iso_code' => 'CF', 'phone_code' => '+236'],
    ['name' => 'Chad', 'iso_code' => 'TD', 'phone_code' => '+235'],
    ['name' => 'Chile', 'iso_code' => 'CL', 'phone_code' => '+56'],
    ['name' => 'China', 'iso_code' => 'CN', 'phone_code' => '+86'],
    ['name' => 'Colombia', 'iso_code' => 'CO', 'phone_code' => '+57'],
    ['name' => 'Comoros', 'iso_code' => 'KM', 'phone_code' => '+269'],
    ['name' => 'Congo', 'iso_code' => 'CG', 'phone_code' => '+242'],
    ['name' => 'Costa Rica', 'iso_code' => 'CR', 'phone_code' => '+506'],
    ['name' => 'Croatia', 'iso_code' => 'HR', 'phone_code' => '+385'],
    ['name' => 'Cuba', 'iso_code' => 'CU', 'phone_code' => '+53'],
    ['name' => 'Cyprus', 'iso_code' => 'CY', 'phone_code' => '+357'],
    ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'phone_code' => '+420'],
    ['name' => 'Denmark', 'iso_code' => 'DK', 'phone_code' => '+45'],
    ['name' => 'Djibouti', 'iso_code' => 'DJ', 'phone_code' => '+253'],
    ['name' => 'Dominica', 'iso_code' => 'DM', 'phone_code' => '+1767'],
    ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'phone_code' => '+1'],
    ['name' => 'Ecuador', 'iso_code' => 'EC', 'phone_code' => '+593'],
    ['name' => 'Egypt', 'iso_code' => 'EG', 'phone_code' => '+20'],
    ['name' => 'El Salvador', 'iso_code' => 'SV', 'phone_code' => '+503'],
    ['name' => 'Estonia', 'iso_code' => 'EE', 'phone_code' => '+372'],
    ['name' => 'Ethiopia', 'iso_code' => 'ET', 'phone_code' => '+251'],
    ['name' => 'Finland', 'iso_code' => 'FI', 'phone_code' => '+358'],
    ['name' => 'France', 'iso_code' => 'FR', 'phone_code' => '+33'],
    ['name' => 'Germany', 'iso_code' => 'DE', 'phone_code' => '+49'],
    ['name' => 'Ghana', 'iso_code' => 'GH', 'phone_code' => '+233'],
    ['name' => 'Greece', 'iso_code' => 'GR', 'phone_code' => '+30'],
    ['name' => 'Hong Kong', 'iso_code' => 'HK', 'phone_code' => '+852'],
    ['name' => 'Hungary', 'iso_code' => 'HU', 'phone_code' => '+36'],
    ['name' => 'Iceland', 'iso_code' => 'IS', 'phone_code' => '+354'],
    ['name' => 'India', 'iso_code' => 'IN', 'phone_code' => '+91'],
    ['name' => 'Indonesia', 'iso_code' => 'ID', 'phone_code' => '+62'],
    ['name' => 'Iran', 'iso_code' => 'IR', 'phone_code' => '+98'],
    ['name' => 'Iraq', 'iso_code' => 'IQ', 'phone_code' => '+964'],
    ['name' => 'Ireland', 'iso_code' => 'IE', 'phone_code' => '+353'],
    ['name' => 'Israel', 'iso_code' => 'IL', 'phone_code' => '+972'],
    ['name' => 'Italy', 'iso_code' => 'IT', 'phone_code' => '+39'],
    ['name' => 'Japan', 'iso_code' => 'JP', 'phone_code' => '+81'],
    ['name' => 'Kenya', 'iso_code' => 'KE', 'phone_code' => '+254'],
    ['name' => 'Kuwait', 'iso_code' => 'KW', 'phone_code' => '+965'],
    ['name' => 'Malaysia', 'iso_code' => 'MY', 'phone_code' => '+60'],
    ['name' => 'Maldives', 'iso_code' => 'MV', 'phone_code' => '+960'],
    ['name' => 'Mexico', 'iso_code' => 'MX', 'phone_code' => '+52'],
    ['name' => 'Nepal', 'iso_code' => 'NP', 'phone_code' => '+977'],
    ['name' => 'Netherlands', 'iso_code' => 'NL', 'phone_code' => '+31'],
    ['name' => 'New Zealand', 'iso_code' => 'NZ', 'phone_code' => '+64'],
    ['name' => 'Nigeria', 'iso_code' => 'NG', 'phone_code' => '+234'],
    ['name' => 'Norway', 'iso_code' => 'NO', 'phone_code' => '+47'],
    ['name' => 'Pakistan', 'iso_code' => 'PK', 'phone_code' => '+92'],
    ['name' => 'Philippines', 'iso_code' => 'PH', 'phone_code' => '+63'],
    ['name' => 'Poland', 'iso_code' => 'PL', 'phone_code' => '+48'],
    ['name' => 'Portugal', 'iso_code' => 'PT', 'phone_code' => '+351'],
    ['name' => 'Qatar', 'iso_code' => 'QA', 'phone_code' => '+974'],
    ['name' => 'Romania', 'iso_code' => 'RO', 'phone_code' => '+40'],
    ['name' => 'Russia', 'iso_code' => 'RU', 'phone_code' => '+7'],
    ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'phone_code' => '+966'],
    ['name' => 'Singapore', 'iso_code' => 'SG', 'phone_code' => '+65'],
    ['name' => 'South Africa', 'iso_code' => 'ZA', 'phone_code' => '+27'],
    ['name' => 'South Korea', 'iso_code' => 'KR', 'phone_code' => '+82'],
    ['name' => 'Spain', 'iso_code' => 'ES', 'phone_code' => '+34'],
    ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'phone_code' => '+94'],
    ['name' => 'Sweden', 'iso_code' => 'SE', 'phone_code' => '+46'],
    ['name' => 'Switzerland', 'iso_code' => 'CH', 'phone_code' => '+41'],
    ['name' => 'Thailand', 'iso_code' => 'TH', 'phone_code' => '+66'],
    ['name' => 'Turkey', 'iso_code' => 'TR', 'phone_code' => '+90'],
    ['name' => 'UAE', 'iso_code' => 'AE', 'phone_code' => '+971'],
    ['name' => 'United Kingdom', 'iso_code' => 'GB', 'phone_code' => '+44'],
    ['name' => 'United States of America', 'iso_code' => 'US', 'phone_code' => '+1'],
    ['name' => 'Vietnam', 'iso_code' => 'VN', 'phone_code' => '+84'],
    ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'phone_code' => '+263'],
        ];

        CountryPhoneCode::truncate(); // optional
        CountryPhoneCode::insert($countries);
    }
}
